### ISSUE TITLE
Example betacat.py doesn't run properly

### ISSUE THREAD

**Issue by sunset1995** [IoTtalk/iottalk-core#33]
The original sample code of `betacat.py` will get 403 error from server with reason `Invalid units: u'dB'. It must be a list.`
It work after modifying profile as below
```
betacat = {
    'name': 'BetaCat',
    'idf_list': [['meow', ['dB']]],
    'accept_protos': ['mqtt'],
}
```

**Comment by iblis17** [comment]
That's my bad. Thanks!

**Comment by sunset1995** [comment]
Still two bug in [The Full Example of Device Application](https://github.com/IoTtalk/iottalk-core#the-full-example-of-device-application) (betacat.py) ~

1. Below two line of code are missing causing _NameError_
```
uplink_topic, downlink_topic = response['ctrl_chans']
revision = response['rev']  # the token of online/offline msg
```
2. `client = mqtt.Client()` causing NameError. This line should be `client = Client()`

All things work for me after fixing above two.
